# @format

name: Develop
on:
  push:
    branches: [develop]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Install Sequelize-Cli
        run: npm install sequelize-cli
      # - name: Run Sequelize-Cli Migrate Undo All
      #   run: npx sequelize db:migrate:undo:all --env production
      - name: Drop Database
        run: npx sequelize db:drop --env production
      - name: Create Database
        run: npx sequelize db:create --env production
      - name: Run Sequelize-Cli Migrate
        run: npx sequelize db:migrate --env production
      - name: Run Sequelize-Cli Seed
        run: npx sequelize db:seed:all --env production
      # - name: Run tests
      #   run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 'b6fe5b9e-7c30-4f83-9a09-277da36913ff'
          heroku_app_name: 'secondhandbe'
          heroku_email: 'maulanaimammalik4@gmail.com'
